### ISSUE TITLE
Update Readme and Rename Screenshots folder to Assets.

### ISSUE THREAD

**Issue by pushpinderpalsingh** [pushpinderpalsingh/SpaceDash#27]
Update README to have the latest Screenshots. And Change the name of the Screenshots folder to Assets. If you do not have access to an iOS Device, do let me know I will send you fresh new Screenshots.

**Comment by gokulkannan7** [comment]
Hi!! I would love to work on this issue

**Comment by gokulkannan7** [comment]
Hey, I would like to make these changes!

**Comment by gokulkannan7** [comment]
I don't have access to any ios device, it would be nice if you could send the screenshots

**Comment by pushpinderpalsingh** [comment]
Sure thing. I will be adding screenshots soon

**Comment by pushpinderpalsingh** [comment]
![Screenshot 2020-09-26 at 9 03 37 PM](https://user-images.githubusercontent.com/47032662/94344308-f5b0b080-003b-11eb-991f-709476dfac04.png) ![Screenshot 2020-09-26 at 9 03 49 PM](https://user-images.githubusercontent.com/47032662/94344309-f8130a80-003b-11eb-87b9-40cacf77415c.png) ![Screenshot 2020-09-26 at 9 03 53 PM](https://user-images.githubusercontent.com/47032662/94344310-f9443780-003b-11eb-9898-6788014c8174.png)

You should crop the tap bar which says iPhone 11

**Comment by ryanvarghese** [comment]
Sir , i would love to do this !
Do let me know whether you will be willing to assign this task to me.

**Comment by pushpinderpalsingh** [comment]
@ryanvarghese I have currently assigned this task to @gokulkannan7, I think he is currently working on it. If I feel like no work has been done, I can definitely assign it to you. I will be posting more such simple tasks, so I would recommend keeping this repo in your watching list. 
Also while you are here. Do star the repo.

**Comment by gokulkannan7** [comment]
yes sir, i am working on it, will update you soon

**Comment by gokulkannan7** [comment]
Sir the quality of the pics is decreasing on my laptop when I download it

**Comment by ryanvarghese** [comment]
> @ryanvarghese I have currently assigned this task to @gokulkannan7, I think he is currently working on it. If I feel like no work has been done, I can definitely assign it to you. I will be posting more such simple tasks, so I would recommend keeping this repo in your watching list.
> Also while you are here. Do star the repo.

Okay no problem. Will star your repo!

**Comment by pushpinderpalsingh** [comment]
@gokulkannan7 you can download screenshots from this Drive link https://drive.google.com/drive/folders/1tt0sy6V4pUdci7bYwpl_5dVuDNaMuayY?usp=sharing

**Comment by gokulkannan7** [comment]
Sir, since this PR is a part of hacktoberfest, can I open the PR on Oct 1?

**Comment by pushpinderpalsingh** [comment]
cool no problems

**Comment by clarkeben** [comment]
A few considerations, @pushpinderpalsingh :
- Remove unnecessary full stops from bullet points
- Typos, maybe run the text through Grammarly  
> A huge shoutout to r/SpaceX for **there** API
- Remove white space below the image and section

**Comment by pushpinderpalsingh** [comment]
> A few considerations, @pushpinderpalsingh :
> 
> - Remove unnecessary full stops from bullet points
> 
> - Typos, maybe run the text through Grammarly  
> 
> > A huge shoutout to r/SpaceX for **there** API
> 
> - Remove white space below the image and section
> 
> 

That would be awesome. Can you open a new issue and I will assign it to you. While your are doing that, You can maybe proofread all the docs including contributing.md and code of conduct?

**Comment by clarkeben** [comment]
> That would be awesome. Can you open a new issue and I will assign it to you. While your are doing that, You can maybe proofread all the docs including contributing.md and code of conduct?

I've added the issue, I was going to include a consideration for adding a "Technologies" section within the README.md. I could probably figure out the build process from the project files 🙂

**Comment by pushpinderpalsingh** [comment]
> I've added the issue, I was going to include a consideration for adding a "Technologies" section within the README.md. I could probably figure out the build process from the project files 🙂

That would be great. Since you are an iOS Developer, I think you can also add an architecture.md file? Explaining the MVP design pattern this app is using as providing some references where one can learn more about the same?

**Comment by clarkeben** [comment]
> That would be great. Since you are an iOS Developer, I think you can also add an architecture.md file? Explaining the MVP design pattern this app is using as providing some references where one can learn more about the same?

Yeah, more than happy to help! Let me create an additional issue to cover architectural design etc. So the tickets can be separate.

**Comment by pushpinderpalsingh** [comment]
@clarkeben if you want to contribute to iOS App, I would recommend joining slack (The link is in the readme). BTW, while you are here can you star the repo?

**Comment by clarkeben** [comment]
@pushpinderpalsingh yeah I'd love to help out, I've got a few bits on my plate currently - but I'll see what can be done with the current version 😀

**Comment by gokulkannan7** [comment]
@pushpinderpalsingh I have opened a PR, pls do check

**Comment by pushpinderpalsingh** [comment]
Cool let me check

**Comment by pushpinderpalsingh** [comment]
@gokulkannan7 if you are still working on this let me know. If you don't respond within 24 hours, I will assign it to someone else.

**Comment by pushpinderpalsingh** [comment]
Hey, @jamie-brannan can you work on this?

**Comment by jamie-brannan** [comment]
Hello 👋 @pushpinderpalsingh, certainly! Assign this it me please and I'll work on it this week.

**Comment by jamie-brannan** [comment]
Hey @pushpinderpalsingh , commenting to run through some of the objectives for this issue

- [x] Change Screenshot folder to Assets

- [ ] Edit text for spelling and grammar errors

- [ ] Add screen shots ◀️ _A screenshot section, or a features section?_

Are there any other aspects of the README.md you'd like to look at?

**Comment by pushpinderpalsingh** [comment]
You need to remove any and all assets which will not be used. The assets folder should have spaceAgencies.md and two other folders namely Screenshots and Mockups. Screenshots folder should contain the images which are going to be used in Readme while mockups can have images of mockups. While you are editing the Mockups folder, can you also add mockups from issue #23? Make sure the name of the mockup image is relevant to the kind of mockup. 

If you find any spelling and grammatical errors in Readme, sure go ahead and edit that. @jamie-brannan

**Comment by jamie-brannan** [comment]
Certainly, for #23 mockups however...

#### How can I tell the difference between a Screenshoot and a Mockup for this project?

What I'm used to a screenshot is just a capture of what's on the device screen where as a mockup has the screen framed in the device, but `Assets/iPad-Mockup` has pictures I'd categorize as screenshots.

`Assets/collage.png` is a college on mockups ➡️ would you like to keep this as a Mockup?

```sh
├── Download_on_the_App_.png
├── Extended
│   ├── Home_Black.png
│   └── Home_Colour.png
├── about.png
├── collage.png
├── details.png
├── home_black.png
├── home_colour.png
├── iPad-Mockup
│   ├── #1.png
│   ├── #2.png
│   └── #3.png
└── spaceAgencies.md
```

#### What's the preferred image file and size? 

Is there a central Google Drive folder that they're being stored or should I just save them from my browser?

I'd like to keep them as uniform as possible.

**Comment by pushpinderpalsingh** [comment]
Remove everything except iPad-Mockup, spaceAgencies.md, and Download_on_the_App.png. I think it would be fine if you saved them from your browser. You are talking about #23 mockups, right? 

I think you might want to pull the latest version of the repo as recently, we have also added twitter banners.

**Comment by jamie-brannan** [comment]
Okay, that's clear thank you. I'll pass through another commit and submit an PR today once I rebase. 👍
