### ISSUE TITLE
Address typos and grammatical errors within supporting documents

### ISSUE THREAD

**Issue by clarkeben** [pushpinderpalsingh/SpaceDash#28]
Address typos and grammatical errors within the supporting documents:
- README.md
- Contributing.md
- Code of conduct

**Acceptance criteria:**
- Address typos
- Modify grammatical errors
- Remove blank space
- Ensure consistent formating

**Comment by pushpinderpalsingh** [comment]
@all-contributors add @clarkeben for docs
