### ISSUE TITLE
Create an architecture.md file

### ISSUE THREAD

**Issue by clarkeben** [pushpinderpalsingh/SpaceDash#30]
Create an architecture.md file to support development. 

**Acceptance Criteria:**
- Provide information about the current design pattern (MVC)
- References regarding the model, views and controllers
- API information
- JSON parsing

..etc

**Comment by pushpinderpalsingh** [comment]
@clarkeben are you currently working on this?

**Comment by clarkeben** [comment]
@pushpinderpalsingh yeah, I've started this, I am aiming to finish sometime this week.

**Comment by pushpinderpalsingh** [comment]
That's awesome!

**Comment by pushpinderpalsingh** [comment]
Thanks, Ben! I have merged the PR for this issue!
