### ISSUE TITLE
New Launchscreen

### ISSUE THREAD

**Issue by pushpinderpalsingh** [pushpinderpalsingh/SpaceDash#33]
Update the launch screen such that it follows [Apple's Human Interface Guidelines for launch screen](https://developer.apple.com/design/human-interface-guidelines/ios/visual-design/launch-screen). Currently, the launch screen just contains the app logo which adds a bit of unnecessary visual interruption.

**Comment by Luan-BK** [comment]
Hi! May I work on this issue?

**Comment by pushpinderpalsingh** [comment]
Sure thing. I am assigning this issue to you.

**Comment by Shubham0812** [comment]
I'll try it out too @pushpinderpalsingh  :)

**Comment by pushpinderpalsingh** [comment]
@Shubham0812 I don't think we need more than one person on this issue. I will be adding more issues today. Also you can find bugs and report any issues you find. 

@Luan-BK Can you reply so that we know you are working on this?

**Comment by Shubham0812** [comment]
@pushpinderpalsingh yeah, that's true. Sounds good to me :)

**Comment by pushpinderpalsingh** [comment]
I don't think @Luan-BK is working on this, @Shubham0812 do you want to work on this before you create a pr for issue #45?

**Comment by Shubham0812** [comment]
Sure, I'll take this up next. 👍  @pushpinderpalsingh

**Comment by pushpinderpalsingh** [comment]
Ok @Shubham0812 I have assigned this to you

**Comment by Shubham0812** [comment]
![Simulator Screen Shot - iPhone 11 Pro Max - 2020-10-07 at 12 44 18](https://user-images.githubusercontent.com/19903539/95299734-cef44480-089b-11eb-9af6-0be52426e6db.png)

Here's what I've done. I've added the tab bar with unselected items in the LaunchScreen.
It provides a fluid transition to the Home screen.
Do let me know your thoughts on this @pushpinderpalsingh.

**Comment by pushpinderpalsingh** [comment]
@Shubham0812 Can you make it look more like the home screen of our app? I think you should remove the logo and black screen. Check out the launch screens of first party apps, you will know what I am talking about

**Comment by Shubham0812** [comment]
@pushpinderpalsingh which type of apps are you considering? Because on most of them I see the logo- Medium, Netflix, Zomato etc.

**Comment by pushpinderpalsingh** [comment]
The first party one's safari, mail, camera, etc. See the Human Interface Guidelines for Launch Screens. @Shubham0812

**Comment by Shubham0812** [comment]
@pushpinderpalsingh yes I do have read the launch screen guidelines.

You cannot modify the view through code or by adding runtime attributes though. So creating a view in the launch board that looks like the new launches view in the home.storyboard is tough.

**Comment by pushpinderpalsingh** [comment]
Yes I agree. Can you just create a launch screen that has black background with white upcoming launch panel. No texts or images or scroll view. @Shubham0812 

BTW are you on SpaceDash slack? We can have this conversation in a much better and efficient way

**Comment by Shubham0812** [comment]
Cool, I'll try adding that. @pushpinderpalsingh 

Not yet, where do I find the link?

**Comment by pushpinderpalsingh** [comment]
The link is in the read me at the end

**Comment by Shubham0812** [comment]
@pushpinderpalsingh I've added a view, taking the same amount of height as the Upcoming Launches.
What are your thoughts on this?

![Simulator Screen Shot - iPhone 11 Pro Max - 2020-10-08 at 18 00 58](https://user-images.githubusercontent.com/19903539/95458804-57541180-0990-11eb-8a0f-818005ca5418.png)

**Comment by pushpinderpalsingh** [comment]
I think it looks good. Can you convert the status bar black. And make the white view's parent class as upcoming view?

**Comment by Shubham0812** [comment]
@pushpinderpalsingh Sure, I changed the status bar to black, what's the second thing? I didn't quite understand that part.

**Comment by pushpinderpalsingh** [comment]
@Shubham0812 I have designed a custom class that will automatically curve the edges. You can see it under the Controllers under views named UpcomingView. If you click on the white view, and then into identity inspector, you would be able to set a custom class for it. Make it UpcomigView.

**Comment by clarkeben** [comment]
@Shubham0812 @pushpinderpalsingh l missed your message, but it looks good. I will need to test the transition on a device to see how it looks. 

As well as this, we should test launch time speeds using the launch time pane or MetricKit! If performance is affected by the image size we can always compress it.

**Comment by Shubham0812** [comment]
> @Shubham0812 @pushpinderpalsingh l missed your message, but it looks good. I will need to test the transition on a device to see how it looks.
> 
> As well as this, we should test launch time speeds using the launch time pane or MetricKit! If performance is affected by the image size we can always compress it.

oh it's an image, it's a view with the same color :)

**Comment by pushpinderpalsingh** [comment]
Hey @Shubham0812, any progress on the launch screen? I don't think that should take long. @clarkeben and I can test the performance after you have created a PR and get back to you if something needs to be updated!

**Comment by Shubham0812** [comment]
Yeah, I'll do that in the evening, currently I'm outside.

**Comment by Shubham0812** [comment]
<img width="266" alt="Screenshot 2020-10-12 at 2 30 37 PM" src="https://user-images.githubusercontent.com/19903539/95727591-fa11d600-0c97-11eb-8162-5389c2d47fc6.png">
@pushpinderpalsingh  it did not allow me to add UpcomingView to the Launchscreen.

I have removed the class and raised a PR, do look into it and let me know :)

**Comment by pushpinderpalsingh** [comment]
ok I will have a look
