### ISSUE TITLE
Find and List different API's for different Space Agencies.

### ISSUE THREAD

**Issue by pushpinderpalsingh** [pushpinderpalsingh/SpaceDash#34]
As we have plans to integrate more Space Agencies, we would be needing a lot more APIs. Create a new file under the Assets folder (currently named screenshots) if it is not already present there. The file should be using the following format. 

| API | Links | Opensource | Paid |
| ------------- | ------------- | ------------- | ------------- |
| SpaceX  | [Github](https://github.com/r-spacex/SpaceX-API), [Docs](https://docs.spacexdata.com/)  | :white_check_mark: | :heavy_multiplication_x:

**Comment by jamie-brannan** [comment]
Hello! I'd like to participate as a part of Hacktoberfest. Would you like this to be a `.md` document?

**Comment by pushpinderpalsingh** [comment]
Yes. you can name it APIs.md

**Comment by jamie-brannan** [comment]
Fantastic! Please assign it to me, and I'll jump right on it. 👍  Thanks!

**Comment by pushpinderpalsingh** [comment]
I think this is an issue that can benefit from how many people are working on it. So if anyone else wants to add something to the APIs.md file do let me know in the comments!

**Comment by jamie-brannan** [comment]
Hello ! Quick question for you @pushpinderpalsingh , when looking at the [contributing guide](https://github.com/pushpinderpalsingh/SpaceDash/blob/develop/Contributing.md) I do not see anything about branch naming conventions.

This is my first Open Source contribution so I want to double check with you that it's alright for me to create a branch off of `develop` named `documentation/space_agency_api_list` ? Please let me know what's most useful for you and the future of the project. 😄

**Comment by jamie-brannan** [comment]
🚧  Another small bump in the road, I'm currently blocked from creating a branch on this project off of `develop`. May I have access rights please?

I cloned the project and have a local branch ready to push when you are 🚀

**Comment by pushpinderpalsingh** [comment]
You need to fork the project, create changes in your fork then create a pr to my repo. Check the readme of the repo for more information. 

As for the branch naming convention, it can be anything if the name is relevant.

**Comment by jamie-brannan** [comment]
- [ ] PR #43 to be linked to this issue

**Comment by pushpinderpalsingh** [comment]
Although I have accepted your pr, I would still like more API options. Can you still work on it? @jamie-brannan 

Also while you are here, do give a star to the repo. 😃

**Comment by jamie-brannan** [comment]
Thank you so much @pushpinderpalsingh 👍

Absolutely! I count on at least getting the known NASA ones listed and sift through some more.

This seems like a potentially long-term point of refer eve My idea was to start the doc with structure.

**Comment by pushpinderpalsingh** [comment]
That's great. I would recommend joining the slack channel if you are here for the long term and not just Hacktoberfest. Slack makes communication much easier.
