### ISSUE TITLE
Create a NSCache for data returned from API

### ISSUE THREAD

**Issue by pushpinderpalsingh** [pushpinderpalsingh/SpaceDash#35]
Create an NSCache that will store the data sent by API for specific queries which is being used frequently and/or updated rarely. This will decrease the loading times for our app while giving us the ability to easily query the DB for possibly filters and stuff.

**Comment by jkreller** [comment]
Hey @pushpinderpalsingh! I would like to try that one! Which "specific queries" are meant exactly?

**Comment by pushpinderpalsingh** [comment]
Sure thing. I am assigning this to you. While you are here, do 🌟  the repo if you haven't already!!

"Specific Queries" as in sorting and filtering data in various DetailViews (like rockets, launches, etc) based on available criteria. For example, rocket view can be filtered on the basis if it is Active or not,  and be sorted on the Date of the first launch.

I know it's a bit ambiguous, so it would be helpful if you join the slack channel and we can discuss this further.

**Comment by jkreller** [comment]
@pushpinderpalsingh Okay, probably I misunderstood your requirements. I'll join the Slack channel and we can discuss it!

**Comment by pushpinderpalsingh** [comment]
@jkreller That would be great!

**Comment by pushpinderpalsingh** [comment]
Implemented
