### ISSUE TITLE
Design a iPad Specific UI

### ISSUE THREAD

**Issue by pushpinderpalsingh** [pushpinderpalsingh/SpaceDash#45]
**What is your idea/feature:**
Design a different iPad optimized UI.

**Why this is beneficial:**
Currently, there is a common UI for all iOS devices which doesn't use all the extra space in any beneficial way. Creating a special iPad UI will mean that there will be more capable in the iPad App.

**Solutions:**
Design a UI Mockup for iPad.

**Acceptance criteria:**
-UI Mockups (screenshots)

**Additional context**
Make sure the proposed UI follows Apple's Human Interface Guideline.

**Comment by Shubham0812** [comment]
I agree, Ipad UI should be a little different than the iPhone versions. I'm taking this up, let's see what I can do. 😄

**Comment by pushpinderpalsingh** [comment]
cool, I am assigning this to you.

**Comment by Shubham0812** [comment]
@pushpinderpalsingh I've created some designs, let me know your thoughts on the same. 😄 

## Home Page

Optimized layouts for ipads -
* 2 Columns/ Row for the upcoming launches that scrolls vertically.
* Added icons to the Launch date, Launch site containers.
* 2 Columns/ Row for the various categories that scrolls horizontally.
* Increased Font Size for improved readability of text.

![pad1](https://user-images.githubusercontent.com/19903539/95180904-32b93780-07e0-11eb-8ecc-f7e43e2a7e0d.png)

## Details Page

Optimized layouts for iPads- 
* 2 Columns/Row layout for the items under the category.
* Changed the placement of the title for the item, and their active status to improve readability.

![pad2](https://user-images.githubusercontent.com/19903539/95180920-36e55500-07e0-11eb-8fc6-f06839a0e7c7.png)

## About Page
* Removed redundant about text.
* Reordered SpaceDash & SpaceX.
* Increased the readability of the privacy policy and license buttons.

![pad3](https://user-images.githubusercontent.com/19903539/95180925-3a78dc00-07e0-11eb-9db5-d184133ecad9.png)

**Comment by Shubham0812** [comment]
If everything works well, give me write access and I'll create a new branch and raise a PR for the screenshot assets.

**Comment by clarkeben** [comment]
Welcome on board @Shubham0812 🙌

Great design, a few user experience notes for the HomeViewController:
- UI view containing launch date/site/payload.. look clickable is there a way of not making the boxes stand out so much
- Can the categories have an inset so users are aware they can scroll horizontally 

This is just speculation I like the design, any thoughts appreciated @pushpinderpalsingh @Shubham0812

**Comment by pushpinderpalsingh** [comment]
I completely agree with @clarkeben. I was thinking of adding a watch now button for both iphones and ipad under upcoming launch. This button should redirect to any live stream of the launch. Any thoughts? @clarkeben @Shubham0812

Also @Shubham0812 check under issues there is a mockup for Rocket Details page. Do make a ipad version of the same. 

I think with some minor adjustments this design would be ready to implement.

**Comment by Shubham0812** [comment]
@clarkeben good point raised, I've made the necessary changes, and updated the Home page.
@pushpinderpalsingh 

![update1](https://user-images.githubusercontent.com/19903539/95184003-5f6f4e00-07e4-11eb-936c-d639183ae3b9.png)

**Comment by clarkeben** [comment]
@pushpinderpalsingh I think the watch now button could be tackled as a separate feature - we'd need to manage the state so it might be easier creating a new ticket for this 😄 

@Shubham0812 good work 🔥!

**Comment by pushpinderpalsingh** [comment]
Ok, @clarkeben  that would be better. @Shubham0812 You will need to take care of the font styling such that it is the same as the iPhone version.
As for write access is concerned. You need to fork the repo then make changes in that and then create a PR to this repository. Also while you are there, give this repo a star 🌟

**Comment by Shubham0812** [comment]
@pushpinderpalsingh cool I'll fork and give a thumbs up, do you want to the change the font too in the designs?

**Comment by pushpinderpalsingh** [comment]
Nope I don't think that's necessary. Just make sure you get it right in the code

**Comment by Shubham0812** [comment]
@pushpinderpalsingh I've raised a PR for the mockups, this issue was for designing the Mockups right? I'd love to take the creation part too next.

**Comment by pushpinderpalsingh** [comment]
@Shubham0812 I have created a new issue #49 if you comment there, I can assign it to you
