### ISSUE TITLE
Create a Watch now Button for Upcoming Launch

### ISSUE THREAD

**Issue by pushpinderpalsingh** [pushpinderpalsingh/SpaceDash#46]
**What is your idea/feature:**
Add a Watch Now button for Upcoming Launch

**Why this is beneficial:**
A watch now button will help to direct our users to the live stream of the upcoming launch. This will make our app more intuitive.

**Solutions:**
The SpaceX API in most cases returns a Youtube link for most of the upcoming launch. When the link is available there should be a green clickable button for watch now else it should be a greyish non-clickable button. 

**Additional context**
Before making the requested changes in code make a mockup and comment it down below. After it is approved by me only then start with code.

**Comment by rarcilla** [comment]
Hi, I'm interested in contributing to the project! Here are the mockups I made of the buttons:


<img width="589" alt="Screen Shot 2020-10-07 at 12 20 41 AM" src="https://user-images.githubusercontent.com/45868050/95300138-9fa9ed00-0833-11eb-9b35-9626426de427.png" width="100">

Also to confirm, the code required to complete this issue doesn't require handling the api is that right? Ie that info is assumed to be be passed in, and I would just need to handle the logic to show the correct button?

**Comment by pushpinderpalsingh** [comment]
The API calls have been handled although you would need to handle the decoding of the data. As of now decoded doesn't decode the links I believe. 

About the design, can you send me a home screen mockup with this watch now button? I personally don't like the Play button. @rarcilla

**Comment by pushpinderpalsingh** [comment]
Are you thinking of working on it? If yes I will assign this issue to you. @rarcilla

**Comment by rarcilla** [comment]
@pushpinderpalsingh I think I’ll pass on this issue - someone else could take it.

**Comment by pushpinderpalsingh** [comment]
No issues. Great to have you here, anyways 😃

**Comment by jkreller** [comment]
Hey @pushpinderpalsingh! I would like to try that issue! I made the following mockup according to @rarcilla's buttons. The color is taken from the "Active" badge to keep in the apps color scheme. I would reduce the size of the lower buttons ("Rockets", "All launches", ...) to fit the new one. Also I would only display the active button. Is no live stream is active / given I would just not display the button.
![Mockup](https://user-images.githubusercontent.com/33465273/96047338-38182100-0e75-11eb-813c-c97521ea677c.png)

**Comment by pushpinderpalsingh** [comment]
Sure thing. I am assigning this to you. While you are here, do 🌟  the repo if you haven't already!!

I don't think we have enough space to incorporate the watch now button on smaller iPhones. Although if you can find a way to better fit the watch now button on smaller iPhones, I am open to it. I believe reducing the size of the lower buttons might work.
