### ISSUE TITLE
User Customisable App Icon

### ISSUE THREAD

**Issue by pushpinderpalsingh** [pushpinderpalsingh/SpaceDash#47]
**What is your idea/feature:**
Give the user to customize their app icons.

**Why this is beneficial:**
This will give users to customize how they want to see their Dashboard 😉  I am providing some App Icon that users can choose from. You can drop in your recommendation too. Create an option in the About Section (Which will be changed to preference after this is implemented.) where users have the option to customize their app icon.

![2](https://user-images.githubusercontent.com/47032662/95201820-14623480-07fe-11eb-801a-8de8f54435ab.png) ![3](https://user-images.githubusercontent.com/47032662/95201825-162bf800-07fe-11eb-82c8-77491ed9e7f2.png) ![4](https://user-images.githubusercontent.com/47032662/95201829-16c48e80-07fe-11eb-868d-b4d70ea7ea95.png)

These are not full-sized app icons. When you start with this issue, I will provide you with a link with full-sized app icons.

**Comment by rajhraval1** [comment]
I would like to work on this issue.

**Comment by pushpinderpalsingh** [comment]
Sure thing. I am assigning this to you. While you are here, do 🌟  the repo!

**Comment by rajhraval1** [comment]
Can I get the link for full-sized app icons? as mentioned in the description.

**Comment by pushpinderpalsingh** [comment]
Sure. I actually forgot about that. I have actually sent you a zip of the App Icons on slack. Can you confirm if it is unzipping properly?

**Comment by rajhraval1** [comment]
Yes, AppIcons Pack has unzipped properly.

**Comment by pushpinderpalsingh** [comment]
Hey, @rajhraval1 any updates on the issue?

**Comment by rajhraval1** [comment]
Hi @pushpinderpalsingh, the work is already done. Due to my Mac issues not fixed. I am not able to give a PR.

The working is basically as follows:
1) About View Controller is now a table view controller which opens other view controllers (Just like the settings app).
2) Selecting App Icons is shown in a table view controller.

Only thing remaining is fixing a checkmark bug after selecting the icon and closing the app.

**Comment by pushpinderpalsingh** [comment]
Ok cool, no issues. @rajhraval1 do you have access to an alternate machine? I am looking for someone to do issue #67 and I believe you wanted to do the redesign.

Also is it also possible to change the LaunchScreen according to the selected App Icon?

**Comment by rajhraval1** [comment]
My Mac will arrive by today. I actually had backed up in another Xcode Project. Hopefully will do a PR in a day or two.

About the launch screen, I need to have a look.

Also I have commented on issue #67 for assignment.

**Comment by pushpinderpalsingh** [comment]
No worries. I have assigned issue #67 to you.
