### ISSUE TITLE
Write an App Store description

### ISSUE THREAD

**Issue by pushpinderpalsingh** [pushpinderpalsingh/SpaceDash#50]
Update the Description for this app. The current description is present in [this file](https://github.com/pushpinderpalsingh/SpaceDash/blob/develop/fastlane/metadata/en-US/description.txt) edit the same file with the updated description.

**Comment by rarchitgupta** [comment]
What does the updated description have to be?

**Comment by pushpinderpalsingh** [comment]
Maybe proofread and update any grammatical errors or otherwise. I mentioned that I was the lone developer on this app, but that's not the case now. Just run of the mill improvements for the app description.
