### ISSUE TITLE
Design a Banner for SpaceDash twitter

### ISSUE THREAD

**Issue by pushpinderpalsingh** [pushpinderpalsingh/SpaceDash#52]
I have created a twitter page for [SpaceDash](https://twitter.com/SpaceDashApp). Although currently there are no tweets from SpaceDash, I plan to start tweeting soon. The banner should be something related to the app. You can provide Banner in the comments below and if the community likes it, you can add it into the screenshots folder and create a pr.

**Comment by M1zz** [comment]
@pushpinderpalsingh Hi! I want to contribute. can I get this issue?

**Comment by pushpinderpalsingh** [comment]
Sure thing. I am assigning this to you. While you are here, do 🌟  the repo! @M1zz

**Comment by pushpinderpalsingh** [comment]
Solved in PR #56
