### ISSUE TITLE
Add a pop-up for Tentative sign. 

### ISSUE THREAD

**Issue by pushpinderpalsingh** [pushpinderpalsingh/SpaceDash#9]
When the launch is tentative, there will be a little green sign next to the launch date. But it doesn't tell much to the user what it is. I was wishing there could be a little pop-up when we either tap on it which could tell the user what the little T sign is. 
I am attaching the screenshot with the Tentative sign. 

![Simulator Screen Shot - iPhone 11 - 2020-09-30 at 11 41 27](https://user-images.githubusercontent.com/47032662/94649871-3138cc80-0313-11eb-9908-2095391c4e5d.png)

You can toggle this sign by enabling it in HomeViewController.

**Comment by megandsouza03** [comment]
Hello!
I would like to work on this issue, could I start with it? 💻

**Comment by devwaseem** [comment]
Hi. I would like to work on this issue. I already made pop up controllers to show the tentative details. the popup dynamically resizes based on the text content.
<img src="https://user-images.githubusercontent.com/12982964/94907648-1787b880-04be-11eb-9562-8ee22d4e107d.png" width="250px" height="550px"/>
<img src="https://user-images.githubusercontent.com/12982964/94907637-135b9b00-04be-11eb-8941-adbc9f9456cc.png" width="250px" height="550px"/>

**Comment by devwaseem** [comment]
I've added dark mode support too. this is optional since other parts of the app don't support dark mode. I would like to know if you are going to support dark and light mode.

**Comment by pushpinderpalsingh** [comment]
I like @devwaseem's first mockup much better. I have plans to support Dark and light mode but for that, I believe we will need to change a lot of our UI styling

**Comment by devwaseem** [comment]
Cool. I'll leave the dark mode support as is now. Here's how it looks.
<img src="https://user-images.githubusercontent.com/12982964/94913120-5457ad80-04c6-11eb-8106-d95d68cc3fd0.png" width="250px" height="550px"/>
<img src="https://user-images.githubusercontent.com/12982964/94913134-5883cb00-04c6-11eb-979e-1134d52e53bc.png" width="250px" height="550px"/>
